apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: https-app-dep1
  name: https-app-dep1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: https-app-dep1
      run: httpsapp
  template:
    metadata:
      labels:
        app: https-app-dep1
        run: httpsapp
    spec:
      containers:
      - image: jacdenn/ubuntu-httpd-tls:2.4.53
        name: ubuntu-httpd
        env:
        - name: DEPLOY
          value: app-https-app-dep1
        - name: VERSION
          value: v1
        ports:
        - containerPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: https-app-dep2
  name: https-app-dep2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: https-app-dep2
      run: httpsapp
  template:
    metadata:
      labels:
        app: https-app-dep2
        run: httpsapp
    spec:
      containers:
      - image: jacdenn/ubuntu-httpd-tls:2.4.53
        name: ubuntu-httpd
        env:
        - name: DEPLOY
          value: app-https-app-dep2
        - name: VERSION
          value: v2
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dep
  name: https-app-dep-svc
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 443
  selector:
    run: httpsapp
  type: ClusterIP
