apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-app-dep1
  name: http-app-dep1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-app-dep1
      run: app
  template:
    metadata:
      labels:
        app: http-app-dep1
        run: app
    spec:
      containers:
      - image: jacdenn/ubuntu-httpd:2.4.53
        name: ubuntu-httpd
        env:
        - name: DEPLOY
          value: app-http-app-dep1
        - name: VERSION
          value: v1
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-app-dep2
  name: http-app-dep2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-app-dep2
      run: app
  template:
    metadata:
      labels:
        app: http-app-dep2
        run: app
    spec:
      containers:
      - image: jacdenn/ubuntu-httpd:2.4.53
        name: ubuntu-httpd
        env:
        - name: DEPLOY
          value: app-http-app-dep2
        - name: VERSION
          value: v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dep
  name: http-app-dep-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: app
  type: ClusterIP
